parameters:
  env(X_HTTP_REQUEST_ID): ''
  restful_bundle.request_id: '%env(X_HTTP_REQUEST_ID)%'
  restful_bundle.validation.message_map: []
  restful_bundle.validation.snake_case: true
framework:
  serializer:
    enabled: true
services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  RestfulBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection/'
      - '../../Exception/'
      - '../../Handler/MapperExceptionHandler.php'

  RestfulBundle\ParamConverter\MapperConverter:
    tags:
      - { name: request.param_converter, priority: -2, converter: mapper_converter }

  RestfulBundle\ParamConverter\EntityDoctrineParamConverter:
    arguments:
      $expressionLanguage: '@?sensio_framework_extra.converter.doctrine.orm.expression_language.default'
    tags:
      - { name: request.param_converter, converter: flexible_doctrine_converter }

  RestfulBundle\Service\RequestTracker:
    arguments:
      $requestId: '%restful_bundle.request_id%'

  RestfulBundle\Monolog\Processor\RequestIdentifierProcessor:
    arguments:
      $requestId: '%restful_bundle.request_id%'
    tags:
      - { name: monolog.processor }

  RestfulBundle\EventListener\ExceptionListener:
    arguments:
      $logger: '@logger'
      $requestId: '%restful_bundle.request_id%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
      - { name: monolog.logger, channel: api }

  RestfulBundle\Handler\ExceptionHandler:
    arguments: [ "%kernel.debug%" ]
    tags:
      - { name: exception_handler, priority: -100 }

  RestfulBundle\Handler\ValidationHandler:
    arguments: [ "%kernel.debug%", "%restful_bundle.validation.message_map%", "%restful_bundle.validation.snake_case%" ]
    tags:
      - { name: exception_handler, priority: 100 }

  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    tags:
      - { name: serializer.normalizer }